const copy = {
  zh: {
    title: '日志审计',
    hint: '查询已上报的业务操作和配置执行结果。记录范围以服务端采集为准。',
    operations: '操作记录',
    login: '登录日志',
    loginUnavailable: '登录历史查询尚未接入',
    eventType: '事件类型',
    loginActor: '用户',
    source: '来源',
    reason: '原因',
    denied: '已拒绝',
    loginSucceeded: '登录成功',
    loginFailed: '登录失败',
    loginThrottled: '登录受限',
    passwordChanged: '修改密码',
    type: '操作类型',
    actor: '操作人',
    object: '对象',
    result: '结果',
    time: '接收时间',
    search: '查询',
    refresh: '刷新',
    reset: '重置',
    success: '成功',
    failure: '失败',
    info: '信息',
    all: '全部结果',
    details: '查看详情',
    detailTitle: '操作详情',
    unknown: '未记录',
    failed: '记录加载失败，请重试。',
    more: '加载更多',
    eventId: '记录标识',
    resourceId: '对象标识',
    scope: '范围',
    scopeId: '范围标识',
    empty: '当前条件下暂无记录',
    scopeNote: '只展示接口返回的元数据；对话正文、密钥与原始业务内容不在此展示。',
    execution: '配置执行记录',
    executionHint: '查看配置指令的处理状态；保存成功与终端应用成功分别判断。',
    state: '执行状态',
    delivery: '查看执行结果',
    deliveryTitle: '终端执行结果',
    deliveryError: '执行结果暂无法获取，请重试。',
    attempts: '尝试次数',
    completed: '完成时间',
  },
  en: {
    title: 'Audit logs',
    hint: 'Query reported activity and configuration execution. Coverage depends on server collection.',
    operations: 'Activity',
    login: 'Login history',
    loginUnavailable: 'Login history is not connected',
    eventType: 'Event',
    loginActor: 'User',
    source: 'Source',
    reason: 'Reason',
    denied: 'Denied',
    loginSucceeded: 'Signed in',
    loginFailed: 'Sign-in failed',
    loginThrottled: 'Throttled',
    passwordChanged: 'Password changed',
    type: 'Action type',
    actor: 'Actor',
    object: 'Object',
    result: 'Result',
    time: 'Received at',
    search: 'Search',
    refresh: 'Refresh',
    reset: 'Reset',
    success: 'Success',
    failure: 'Failure',
    info: 'Info',
    all: 'All results',
    details: 'Details',
    detailTitle: 'Activity details',
    unknown: 'Not recorded',
    failed: 'Unable to load records. Retry.',
    more: 'Load more',
    eventId: 'Record ID',
    resourceId: 'Object ID',
    scope: 'Scope',
    scopeId: 'Scope ID',
    empty: 'No matching records',
    scopeNote:
      'Only metadata returned by the API is shown. Conversation contents, secrets and raw business data are excluded.',
    execution: 'Configuration execution',
    executionHint: 'Inspect instruction status. Saving configuration does not prove it has been applied.',
    state: 'State',
    delivery: 'Execution results',
    deliveryTitle: 'Client execution results',
    deliveryError: 'Execution results unavailable. Retry.',
    attempts: 'Attempts',
    completed: 'Completed at',
  },
};
export const auditCopy = copy.zh;
export function getAuditCopy(language: keyof typeof copy) {
  return copy[language];
}
