// Digital-employee module copy. `src/admin/i18n.ts` is frozen for this
// work package, so every string the antd rewrite introduces lives here in
// both languages. The main controller can merge `employeesCopy` into the
// shared dictionary later; components read it through `employeesT`.

import type { AdminLanguage } from './i18n.js';

const zh = {
  employeesDesc: '管理负责人、服务对象和能力配置。',
  tabEmployees: '数字员工列表',
  tabRequests: '申请审批',
  colName: '名称',
  colOwner: '负责人',
  colStatus: '状态',
  colModel: '模型',
  colLastUsed: '最近使用',
  lastUsedUnknown: '暂未统计',
  lastUsedHint: '最近使用需要真实活动记录；当前接口未提供，不用创建时间替代。',
  ownerMissing: '待补充负责人',
  phaseReady: '部署就绪',
  phasePending: '部署中',
  phaseSleeping: '休眠中',
  phaseError: '部署失败',
  phaseUnknown: '未知',
  actionManage: '管理',
  actionChat: '测试对话',
  actionView: '查看',
  createTitle: '新建数字员工',
  createDescription: '提交后由门户创建策略决定结果：有权限的管理员直接创建，其他账号进入审批；两种结果分别反馈。',
  createModelLabel: '模型',
  createModelTooltip:
    '按选择顺序决定优先级：第一个为默认模型，其余可按名选用（选择，非自动故障转移）。不选则使用平台默认模型。',
  createModelPlaceholder: '选择模型（可选，多选）',
  createSubmit: '提交创建',
  detailTabBasic: '基本配置',
  detailTabCapabilities: '知识与技能',
  detailTabMemory: '长期记忆',
  detailTabPublish: '发布与使用',
  detailTabRuns: '运行记录',
  labelDisplayName: '显示名称',
  labelTechId: '技术标识',
  labelRuntime: '运行时',
  labelMemoryUser: '记忆用户',
  labelCreatedAt: '创建时间',
  labelModel: '使用模型',
  labelOwner: '负责人',
  editGapTitle: '配置编辑暂未开放',
  editGapDescription: '数字员工暂无配置更新接口；负责人、团队、模型与开放范围的编辑需门户接口支持后开放。',
  capabilitiesGapTitle: '知识与技能关联暂未接入',
  capabilitiesGapDescription:
    '数字员工与知识库、技能的关联接口尚未提供。接入后可在此选择知识库、技能及版本，并查看使用权限与依赖。',
  runsGapTitle: '运行记录暂未接入',
  runsGapDescription: '运行与对话记录需要按范围查询的接口；正文查看需独立内容权限。接入前此页不展示任何记录。',
  publishScope: '使用范围',
  publishScopeUnknown: '未提供（接口暂无）',
  publishScopeGap: '开放范围（可用用户/团队）的配置与鉴权接口暂未提供；门户当前按负责人与管理员校验访问。',
  publishWebEntry: '网页入口',
  publishCopyEntry: '复制入口',
  publishEntryCopied: '已复制网页入口（不含访问令牌）',
  publishWecom: '企业微信',
  publishChannelOn: '已接入',
  publishChannelOff: '未接入',
  publishNote: '「部署就绪」仅表示运行实例可用，不等于发布配置完成或当前模型认证有效。',
  publishRecordTitle: '入口与发布记录',
  publishRecordGap: '发布记录（配置保存/应用/入口生效）接口暂未提供，无法展示历史。',
  publishChannelUnknownName: '渠道名称未提供',
  deleteBlockedTitle: '删除数字员工',
  deleteBlockedNotice: '删除会移除对话入口与运行实例；历史记录和记忆数据的处置策略尚待后端明确。',
  deleteBlockedFacts: '关联知识库与技能会解除关联，不删除其内容；历史与记忆的处置语义待确认。',
  deleteBlockedAction: '处置契约明确前，此处不开放删除确认。需要下线入口时请先联系平台方明确数据处置。',
  deleteBlockedBack: '返回详情',
  requestsTitle: '申请审批',
  requestsDescription: '处理数字员工创建申请，审批结果关联最终实例。',
  requestsFilterAll: '全部',
  requestsFilterPending: '待审批',
  requestsFilterDecided: '已处理',
  requestsColName: '申请名称',
  requestsColRequester: '申请人',
  requestsColTime: '提交时间',
  requestsColState: '审批状态',
  requestsColReason: '理由',
  requestsStatePending: '待审批',
  requestsStateUnknown: '未知状态',
  requestsApprove: '同意',
  requestsReject: '拒绝',
  requestsRejectTitle: '拒绝申请',
  requestsRejectDescription: '申请人将在自己的申请列表中看到拒绝原因。',
  requestsRejectReasonLabel: '拒绝原因',
  requestsRejectReasonRequired: '请填写拒绝原因。',
  requestsDecided: '操作已完成',
  requestsDetailTitle: '申请详情',
  requestsOwnerLabel: '申请人',
  requestsTimeLabel: '提交时间',
  chatNoSession: '会话已过期，请重新登录',
  chatBlockedTitle: '未能自动打开对话',
  chatBlockedMinted: '浏览器拦截了新窗口。会话已就绪，请点击下面的链接进入对话。',
  chatOpenLink: '进入对话（新窗口）',
  chatBlockedFallback: '浏览器拦截了新窗口，且会话直通未成功。请允许本站弹出式窗口后重试；链接不会显示或记录访问令牌。',
  chatRetry: '重试打开',
  memoryFactScope: '记忆归属',
  memoryFactSessions: '会话数',
  memoryFactLastActive: '最近活动',
  memoryFactLastWrite: '最近记忆写入',
  memoryLastWriteUnknown: '暂未采集',
  memoryNotProvisioned: '该员工暂无记忆指标（未在记忆服务中返回）',
  memorySessionsNote: '会话数不是记忆条数；最近活动不等于最近记忆写入。',
  notProvided: '未提供',
} as const;

const en: Record<keyof typeof zh, string> = {
  employeesDesc: 'Manage owners, audiences, and capability configuration.',
  tabEmployees: 'Digital employees',
  tabRequests: 'Requests & approvals',
  colName: 'Name',
  colOwner: 'Owner',
  colStatus: 'Status',
  colModel: 'Model',
  colLastUsed: 'Last used',
  lastUsedUnknown: 'No data yet',
  lastUsedHint:
    'Last-used requires real activity records; the API does not provide them yet, so creation time is not substituted.',
  ownerMissing: 'Owner to be assigned',
  phaseReady: 'Deployed',
  phasePending: 'Deploying',
  phaseSleeping: 'Hibernating',
  phaseError: 'Failed',
  phaseUnknown: 'Unknown',
  actionManage: 'Manage',
  actionChat: 'Test chat',
  actionView: 'View',
  createTitle: 'New digital employee',
  createDescription:
    'The portal creation policy decides the outcome: administrators with permission create directly, everyone else enters approval; each result is reported separately.',
  createModelLabel: 'Models',
  createModelTooltip:
    'Priority follows selection order: the first pick is the default model; the rest are selectable by name (selection, not automatic failover). Leave empty for the platform default.',
  createModelPlaceholder: 'Pick models (optional, multiple)',
  createSubmit: 'Submit',
  detailTabBasic: 'Basics',
  detailTabCapabilities: 'Knowledge & skills',
  detailTabMemory: 'Long-term memory',
  detailTabPublish: 'Publishing & usage',
  detailTabRuns: 'Run history',
  labelDisplayName: 'Display name',
  labelTechId: 'Technical ID',
  labelRuntime: 'Runtime',
  labelMemoryUser: 'Memory user',
  labelCreatedAt: 'Created',
  labelModel: 'Model',
  labelOwner: 'Owner',
  editGapTitle: 'Editing not available yet',
  editGapDescription:
    'There is no update API for digital employees; editing owner, team, model, or audience opens once the portal provides it.',
  capabilitiesGapTitle: 'Knowledge & skill bindings not wired',
  capabilitiesGapDescription:
    'The binding API between digital employees and knowledge bases or skills is not available. Once it lands, you can pick bases, skills, and versions here and inspect permissions and dependencies.',
  runsGapTitle: 'Run history not wired',
  runsGapDescription:
    'Runs and conversations need a scope-aware query API, and transcripts need separate content permission. Nothing is listed here before that lands.',
  publishScope: 'Audience',
  publishScopeUnknown: 'Not provided (no API yet)',
  publishScopeGap:
    'Audience configuration and enforcement APIs are not available; the portal currently authorises owner or admin access.',
  publishWebEntry: 'Web entry',
  publishCopyEntry: 'Copy entry',
  publishEntryCopied: 'Web entry copied (no access token included)',
  publishWecom: 'WeCom',
  publishChannelOn: 'Connected',
  publishChannelOff: 'Not connected',
  publishNote:
    '"Deployed" only means the runtime instance is ready; it does not imply publishing finished or the model credential is valid.',
  publishRecordTitle: 'Entries & publish records',
  publishRecordGap: 'Publish records (save/apply/entry activation) have no API yet, so no history is shown.',
  publishChannelUnknownName: 'Channel name not provided',
  deleteBlockedTitle: 'Delete digital employee',
  deleteBlockedNotice:
    'Deleting removes the chat entry and the runtime instance; how history and memory data are disposed is still to be defined by the backend.',
  deleteBlockedFacts:
    'Linked knowledge bases and skills are unlinked, their content is kept; disposal semantics for history and memory are unconfirmed.',
  deleteBlockedAction:
    'Until the disposal contract is defined, delete confirmation stays unavailable. Contact the platform team to clarify data disposal before taking an employee offline.',
  deleteBlockedBack: 'Back to detail',
  requestsTitle: 'Requests & approvals',
  requestsDescription: 'Process digital-employee creation requests; decisions link to the resulting instance.',
  requestsFilterAll: 'All',
  requestsFilterPending: 'Pending',
  requestsFilterDecided: 'Decided',
  requestsColName: 'Request',
  requestsColRequester: 'Requester',
  requestsColTime: 'Submitted',
  requestsColState: 'State',
  requestsColReason: 'Reason',
  requestsStatePending: 'Pending',
  requestsStateUnknown: 'Unknown state',
  requestsApprove: 'Approve',
  requestsReject: 'Reject',
  requestsRejectTitle: 'Reject request',
  requestsRejectDescription: 'The requester will see the rejection reason in their own request list.',
  requestsRejectReasonLabel: 'Rejection reason',
  requestsRejectReasonRequired: 'Enter a rejection reason.',
  requestsDetailTitle: 'Request detail',
  requestsOwnerLabel: 'Requester',
  requestsTimeLabel: 'Submitted',
  requestsDecided: 'Done',
  chatNoSession: 'Session expired, sign in again',
  chatBlockedTitle: 'Could not open chat automatically',
  chatBlockedMinted:
    'The browser blocked the new window. The session is ready — use the link below to enter the conversation.',
  chatOpenLink: 'Enter conversation (new window)',
  chatBlockedFallback:
    'The browser blocked the new window and the silent handoff failed. Allow pop-ups for this site and retry; the access token is never displayed or logged.',
  chatRetry: 'Retry',
  memoryFactScope: 'Memory scope',
  memoryFactSessions: 'Sessions',
  memoryFactLastActive: 'Last activity',
  memoryFactLastWrite: 'Last memory write',
  memoryLastWriteUnknown: 'Not collected',
  memoryNotProvisioned: 'No memory metrics for this employee (not returned by the memory service)',
  memorySessionsNote: 'Session count is not memory count; last activity is not the last memory write.',
  notProvided: 'Not provided',
};

export const employeesCopy: Record<AdminLanguage, Record<keyof typeof zh, string>> = { zh, en };

export type EmployeesCopyKey = keyof typeof zh;

export function employeesT(key: EmployeesCopyKey, language: AdminLanguage = 'zh'): string {
  return employeesCopy[language][key];
}
