// Page copy for the account-mapping work area (formerly "identity alignment").
// Kept out of i18n.ts (owned by the shell); the main controller merges these
// entries when the shared dictionary is ready.
const copy = {
  zh: {
    pageTitle: '账号关联',
    pageDescription: '将企业微信、飞书等外部账号关联到平台用户，用于识别来访员工。账号关联不是单点登录或组织同步。',
    sourceListTitle: '来源平台',
    sourceKindColumn: '类型',
    manageLinks: '管理关联',
    linksFor: '账号关联',
    backToSources: '返回来源平台',
    platformUser: '平台用户',
    linkTime: '关联时间',
    linkTimeUnknown: '未知',
    linkActive: '已关联',
    linkDisabled: '已停用',
    addLink: '关联账号',
    addLinkTitle: '关联外部账号',
    editLinkTitle: '编辑账号关联',
    externalAccount: '外部账号',
    selectPlatformUser: '选择平台用户',
    selectPlatformUserPlaceholder: '搜索姓名或账号',
    noOverwriteNote: '同一来源中的外部账号不能静默覆盖到另一用户；变更前请核对当前绑定与影响，变更会记录到操作日志。',
    unlink: '解除关联',
    unlinkTitle: '解除账号关联',
    unlinkImpact: '解除后无法通过该关联识别企业成员，企业数据访问将被拒绝；平台账号与已有资料不删除。',
    confirmUnlink: '确认解除',
    linksEmpty: '暂无关联账号',
    linksEmptyHint: '将该来源的外部账号关联到平台用户后在此展示。',
    linksLoadFailed: '账号关联加载失败',
    userUnknown: '未知用户',
    retry: '重试',
    ok: '确定',
    searchPlaceholder: '搜索外部账号或用户',
    filterAll: '全部',
    sourcesEmpty: '暂无来源平台',
    sourcesEmptyHint: '新增来源平台后，可将其外部账号关联到平台用户。',
    sourcesLoadFailed: '来源平台加载失败，请稍后重试。',
    addSource: '新增来源平台',
    addSourceTitle: '新增来源平台',
    sourceIdLabel: '来源标识',
    sourceIdPlaceholder: '例如 wecom-directory',
    sourceNameLabel: '名称',
    sourceKindLabel: '类型',
    sourceIdInvalid: '来源标识只能包含字母、数字、点、下划线或连字符，长度 1-100。',
    sourceNameRequired: '请填写名称。',
    sourceCreateFailed: '来源平台创建失败，请稍后重试。',
    sourceCreated: '来源平台已创建。',
    mappingExternalIdRequired: '请填写外部账号。',
    mappingUserRequired: '请填写或选择平台用户。',
    mappingSaveFailed: '账号关联保存失败，请稍后重试。',
    mappingSaved: '账号关联已保存。',
    mappingDeleteFailed: '账号关联解除失败，请稍后重试。',
    mappingRemoved: '账号关联已解除，变更已记录到操作日志。',
    bindingConflictTitle: '该外部账号已绑定其他用户',
    bindingConflictCurrent: '当前绑定',
    bindingConflictNext: '保存后绑定',
    bindingConflictConfirm: '确认变更绑定',
    partialSourcesFailed: '部分来源平台的关联加载失败，当前列表可能不完整。',
    userNamesUnavailable: '当前账号无权查看用户列表，平台用户仅显示 ID。',
  },
  en: {
    pageTitle: 'Account mappings',
    pageDescription:
      'Link external accounts such as WeCom or Feishu to platform users to identify visiting employees. Account mapping is not SSO or directory sync.',
    sourceListTitle: 'Platforms',
    sourceKindColumn: 'Type',
    manageLinks: 'Manage mappings',
    linksFor: 'Account mappings',
    backToSources: 'Back to platforms',
    platformUser: 'Platform user',
    linkTime: 'Linked at',
    linkTimeUnknown: 'Unknown',
    linkActive: 'Linked',
    linkDisabled: 'Disabled',
    addLink: 'Link account',
    addLinkTitle: 'Link external account',
    editLinkTitle: 'Edit account mapping',
    externalAccount: 'External account',
    selectPlatformUser: 'Select platform user',
    selectPlatformUserPlaceholder: 'Search name or account',
    noOverwriteNote:
      'An external account must not silently move to another user. Review the current binding and its impact before changing; changes are audited.',
    unlink: 'Unlink',
    unlinkTitle: 'Unlink account',
    unlinkImpact:
      'After unlinking, this mapping no longer identifies an enterprise member and enterprise data access is rejected. The platform account and existing data are kept.',
    confirmUnlink: 'Confirm unlink',
    linksEmpty: 'No account mappings',
    linksEmptyHint: 'Link external accounts from this platform to platform users to see them here.',
    linksLoadFailed: 'Account mappings failed to load',
    userUnknown: 'Unknown user',
    retry: 'Retry',
    ok: 'OK',
    searchPlaceholder: 'Search external account or user',
    filterAll: 'All',
    sourcesEmpty: 'No source platforms',
    sourcesEmptyHint: 'Add a source platform, then link its external accounts to platform users.',
    sourcesLoadFailed: 'Source platforms failed to load. Try again later.',
    addSource: 'Add platform',
    addSourceTitle: 'Add source platform',
    sourceIdLabel: 'Source ID',
    sourceIdPlaceholder: 'for example wecom-directory',
    sourceNameLabel: 'Name',
    sourceKindLabel: 'Type',
    sourceIdInvalid: 'Source ID may only contain letters, digits, dot, underscore and hyphen, length 1-100.',
    sourceNameRequired: 'Enter a name.',
    sourceCreateFailed: 'Failed to create the source platform. Try again later.',
    sourceCreated: 'Source platform created.',
    mappingExternalIdRequired: 'Enter the external account.',
    mappingUserRequired: 'Enter or select the platform user.',
    mappingSaveFailed: 'Failed to save the account mapping. Try again later.',
    mappingSaved: 'Account mapping saved.',
    mappingDeleteFailed: 'Failed to unlink the account mapping. Try again later.',
    mappingRemoved: 'Account mapping unlinked; the change is recorded in the operation log.',
    bindingConflictTitle: 'This external account is already bound to another user',
    bindingConflictCurrent: 'Current binding',
    bindingConflictNext: 'Binding after save',
    bindingConflictConfirm: 'Confirm rebinding',
    partialSourcesFailed: 'Mappings for some source platforms failed to load; this list may be incomplete.',
    userNamesUnavailable: 'This account cannot list users; platform users are shown by ID only.',
  },
} as const;
export const identityCopy = copy.zh;
export type IdentityCopyKey = keyof (typeof copy)['zh'];
export function getIdentityCopy(language: keyof typeof copy) {
  return copy[language];
}
