// Enterprise-model module copy. `src/admin/i18n.ts` is frozen for this
// work package, so every string the antd rewrite introduces lives here in
// both languages. The main controller can merge `modelsCopy` into the
// shared dictionary later; components read it through `modelsT`.

import type { AdminLanguage } from './i18n.js';

const zh = {
  modelsListTitle: '模型列表',
  modelsListDescription: '配置模型、可用范围，并区分保存、应用与检测结果。',
  colModel: '模型',
  colUpstream: '上游模型',
  colManageState: '管理状态',
  colConfigState: '配置状态（网关）',
  colTestState: '检测结果',
  stateEnabled: '已启用',
  stateDisabled: '已停用',
  testNotRun: '未检测',
  testGapHint: '模型调用检测接口暂未提供。保存成功只代表配置已持久化，不代表已应用或可调用。',
  configPending: '待应用',
  configApplying: '应用中',
  configApplied: '已应用',
  configDegraded: '部分异常',
  configError: '应用失败',
  configUnknown: '状态未知',
  configLoadFailed: '获取失败',
  configTargetRevision: '目标版本',
  configAppliedRevision: '已应用版本',
  configLastSync: '最近同步',
  configGatewayState: '网关同步状态',
  configRouteIncluded: '本模型路由：已包含',
  configRouteMissing: '本模型路由：未包含',
  configRouteMissingHint: '该模型未出现在网关期望状态中，可能尚未经网关发布（或走非网关路径）。',
  configNotConfirmed: '网关尚未回报已观测版本；当前运行配置未知，不默认视为已应用。',
  configLoadFailedHint: '网关同步状态获取失败，不能据此判断配置生效结果。',
  configNoPermission: '无权限查看',
  configNoPermissionTitle: '配置生效详情需要运维权限',
  configNoPermissionHint:
    '当前账号未获授权查看网关同步状态；此页不展示技术状态，也不会代替运维发起查询。如需排查请联系系统运维人员。',
  detailTabBasic: '基本信息',
  detailTabAccess: '使用权限',
  detailTabEmployees: '关联数字员工',
  detailTabStatus: '配置生效详情',
  labelModelId: '模型标识',
  labelUpstream: '上游模型名称',
  labelProtocol: '协议',
  labelSource: '来源',
  labelCredential: '接入配置',
  labelCredentialMissing: '未关联（在「接入配置」中维护）',
  labelCapabilities: '能力标签',
  labelExecutionService: '执行服务',
  executionServiceGateway: '模型网关（期望状态同步）',
  credentialNote: 'API Key 等密钥不在模型页维护；请在「接入配置」更新，模型通过引用复用。',
  accessColSubject: '授权对象',
  accessColType: '类型',
  accessColTime: '授权时间',
  accessEmpty: '暂无授权对象',
  accessHint: '使用权限只允许调用模型，不交付上游密钥。',
  associatedGapTitle: '关联数字员工暂未接入',
  associatedGapDescription:
    '数字员工与模型的关联关系需要门户员工接口；接入后在此展示受配置变更影响的数字员工。',
  statusAlertTitle: '保存、应用、检测分别判断',
  statusAlertDescription:
    '保存成功只证明配置持久化；网关回报版本后才算已应用；实际调用检测通过才算检测成功。旧版本检测结果不能证明新配置可用。',
  statusTimelineSaved: '期望状态已保存',
  statusTimelineApplied: '网关已应用',
  statusTimelineNotApplied: '尚未确认应用',
  deleteImpactAssignments: '当前授权对象数',
  disableImpact: '停用后新的模型调用将被拒绝；授权记录保留。',
  searchPlaceholder: '搜索模型名称或标识',
  subjectTypeUser: '用户',
  subjectTypeRole: '角色',
  subjectTypeTeam: '团队',
  accessAction: '调整可用范围',
  grantSelectedCount: '已选对象',
  notProvided: '未提供',
  configRefresh: '刷新生效状态',
  publishAction: '发布生效',
  publishConfirmTitle: '从模型目录发布网关路由',
  publishConfirmDescription: '按当前模型目录派生并原子替换网关期望路由；仅收录已启用且映射完整（网关地址与上游模型齐全）的模型。',
  publishExcluded: '以下模型不会被收录',
  publishExcludedDisabled: '未启用',
  publishExcludedIncomplete: '映射不完整',
  publishSucceeded: '已发布，等待网关应用',
  publishFailed: '发布失败',
  driftMissing: '待发布',
  driftMissingHint: '该模型已启用且映射完整，但不在网关期望路由中；请执行「发布生效」。',
  driftMismatched: '配置不一致',
  driftMismatchedHint: '网关期望路由与目录派生结果不一致；请执行「发布生效」。',
  catalogPublishState: '目录发布状态',
  catalogPublishIncluded: '已收录',
  catalogPublishSkipped: '不收录（未启用或映射不完整）',
  driftFields: '不一致字段',
  fieldEnabled: '启用状态',
  fieldEndpoint: '网关地址',
  fieldUpstreamModel: '上游模型',
  fieldProviderType: '提供者',
  fieldCredentialRef: '接入引用',
} as const;

const en: Record<keyof typeof zh, string> = {
  modelsListTitle: 'Models',
  modelsListDescription: 'Configure models and audiences; keep save, apply, and detection results separate.',
  colModel: 'Model',
  colUpstream: 'Upstream model',
  colManageState: 'Managed state',
  colConfigState: 'Config state (gateway)',
  colTestState: 'Detection',
  stateEnabled: 'Enabled',
  stateDisabled: 'Disabled',
  testNotRun: 'Not tested',
  testGapHint: 'No model invocation test API yet. A successful save only means the config is persisted — not applied or callable.',
  configPending: 'Pending apply',
  configApplying: 'Applying',
  configApplied: 'Applied',
  configDegraded: 'Degraded',
  configError: 'Apply failed',
  configUnknown: 'Unknown',
  configLoadFailed: 'Load failed',
  configTargetRevision: 'Target revision',
  configAppliedRevision: 'Applied revision',
  configLastSync: 'Last sync',
  configGatewayState: 'Gateway sync state',
  configRouteIncluded: 'Route for this model: included',
  configRouteMissing: 'Route for this model: missing',
  configRouteMissingHint: 'The model is absent from the gateway desired state; it may not be published through the gateway (or uses a non-gateway path).',
  configNotConfirmed: 'The gateway has not reported an observed revision; the running config is unknown and is not treated as applied.',
  configLoadFailedHint: 'Gateway sync state could not be loaded; config effectiveness cannot be judged from this.',
  configNoPermission: 'No permission',
  configNoPermissionTitle: 'Config effectiveness requires ops permission',
  configNoPermissionHint:
    'This account is not authorised to view gateway sync state; the technical status is not shown here and no query is issued on your behalf. Contact your system operators to investigate.',
  detailTabBasic: 'Basics',
  detailTabAccess: 'Access',
  detailTabEmployees: 'Linked digital employees',
  detailTabStatus: 'Config effectiveness',
  labelModelId: 'Model ID',
  labelUpstream: 'Upstream model name',
  labelProtocol: 'Protocol',
  labelSource: 'Source',
  labelCredential: 'Connection',
  labelCredentialMissing: 'Not linked (maintained under "Connections")',
  labelCapabilities: 'Capabilities',
  labelExecutionService: 'Execution service',
  executionServiceGateway: 'Model gateway (desired-state sync)',
  credentialNote: 'API keys are not maintained on the model page; update them under "Connections" — models reuse them by reference.',
  accessColSubject: 'Subject',
  accessColType: 'Type',
  accessColTime: 'Granted',
  accessEmpty: 'No assigned subjects',
  accessHint: 'Model access grants invocation only, never upstream keys.',
  associatedGapTitle: 'Linked digital employees not wired',
  associatedGapDescription:
    'The model-to-employee relationship needs the portal employee API; once wired, employees affected by config changes are listed here.',
  statusAlertTitle: 'Save, apply, and detect are judged separately',
  statusAlertDescription:
    'A successful save only persists configuration; applied requires the gateway-reported revision; detected requires a real invocation. A previous revision\'s test result does not validate the new config.',
  statusTimelineSaved: 'Desired state saved',
  statusTimelineApplied: 'Applied by gateway',
  statusTimelineNotApplied: 'Application unconfirmed',
  deleteImpactAssignments: 'Assigned subjects',
  disableImpact: 'New model calls will be rejected after disabling; assignments are kept.',
  searchPlaceholder: 'Search model name or ID',
  subjectTypeUser: 'User',
  subjectTypeRole: 'Role',
  subjectTypeTeam: 'Team',
  accessAction: 'Adjust audience',
  grantSelectedCount: 'Selected subjects',
  notProvided: 'Not provided',
  configRefresh: 'Refresh status',
  publishAction: 'Publish routes',
  publishConfirmTitle: 'Publish gateway routes from the model catalog',
  publishConfirmDescription: 'Derives gateway routes from the current model catalog and atomically replaces the desired routes; only enabled models with complete mapping (gateway endpoint and upstream model) are included.',
  publishExcluded: 'Excluded from publishing',
  publishExcludedDisabled: 'disabled',
  publishExcludedIncomplete: 'incomplete mapping',
  publishSucceeded: 'Published; waiting for the gateway to apply',
  publishFailed: 'Publish failed',
  driftMissing: 'Pending publish',
  driftMissingHint: 'The model is enabled with complete mapping but is absent from the desired gateway routes; run "Publish routes".',
  driftMismatched: 'Config drift',
  driftMismatchedHint: 'The desired gateway route differs from the catalog-derived route; run "Publish routes".',
  catalogPublishState: 'Catalog publish state',
  catalogPublishIncluded: 'Included',
  catalogPublishSkipped: 'Excluded (disabled or incomplete mapping)',
  driftFields: 'Differing fields',
  fieldEnabled: 'enabled state',
  fieldEndpoint: 'gateway endpoint',
  fieldUpstreamModel: 'upstream model',
  fieldProviderType: 'provider type',
  fieldCredentialRef: 'credential reference',
};

export const modelsCopy: Record<AdminLanguage, Record<keyof typeof zh, string>> = { zh, en };

export type ModelsCopyKey = keyof typeof zh;

export function modelsT(key: ModelsCopyKey, language: AdminLanguage = 'zh'): string {
  return modelsCopy[language][key];
}
