// Page copy for product licensing, login sessions, connection configuration
// and configuration-application status. Kept out of i18n.ts (owned by the
// shell); the main controller merges these entries when the shared dictionary
// is ready.
const copy = {
  zh: {
    licensesTitle: '产品授权',
    licensesDescription: '查看授权版本、范围、状态与有效期。',
    importLicenseAction: '导入授权',
    licenseValid: '有效',
    licenseRevoked: '已撤销',
    validUntil: '有效期至',
    perpetual: '永久',
    graceUntil: '宽限期至',
    userScope: '用户范围',
    moduleScope: '模块范围',
    licenseDetail: '授权详情',
    issuedAtLabel: '签发时间',
    revokeLicenseImpact: '撤销后该授权立即失效；请确认已有替代授权，避免功能受限。',
    licenseImportNote: '导入会校验签名、部署绑定与有效期；校验失败时现有有效授权不会被覆盖。',
    sessionsTitle: '登录会话',
    sessionsDescription: '查看有效登录与设备信息，按需撤销。有效登录凭证不等于此刻在线。',
    clientColumn: '客户端 / 设备',
    clientUnknown: '未知',
    lastActive: '最近活动',
    sessionStateActive: '有效',
    sessionStateRevoked: '已撤销',
    revokeLogin: '撤销登录',
    revokeLoginTitle: '撤销本次登录',
    revokeLoginImpact: '撤销后该客户端需要重新登录；不删除历史操作记录。',
    confirmRevokeLogin: '确认撤销',
    sessionDetail: '会话详情',
    sessionSubject: '主题',
    sessionCreatedAt: '创建时间',
    sessionRevokedAt: '撤销时间',
    credentialsTitle: '接入配置',
    credentialsDescription: '模型等服务的接入与认证信息统一维护和复用。密钥只写入服务端，界面不回显原值。',
    addConnection: '新建接入配置',
    serviceColumn: '服务',
    authColumn: '认证信息',
    authSet: '已设置，不可回显',
    referencedModels: '引用模型',
    connectionCheck: '连接检测',
    checkUnknown: '未知',
    valueUnknown: '未知',
    notCollected: '暂未统计',
    updateKey: '更新密钥',
    updateKeyTitle: '更新密钥',
    updateKeyNote: '不会显示原密钥；空值不能覆盖已有密钥。保存后请到配置生效详情跟踪应用与检测结果。',
    newKey: '新密钥',
    configSaved: '配置已保存',
    savedNotApplied: '保存成功仅表示配置已持久化，不代表已应用或检测通过。',
    connectionDetail: '接入详情',
    usageSubjects: '使用对象',
    grantAccess: '授权',
    rotateRetryNote: '轮换失败，密钥未变更。可修正后重试。',
    statusTitle: '配置生效详情',
    statusDescription: '目标版本、已应用版本与同步结果。保存、应用、检测是不同阶段。',
    desiredRevision: '目标版本',
    appliedRevision: '已应用版本',
    publishedAt: '发布时间',
    configState: '配置状态',
    lastSync: '最近同步',
    executor: '执行服务',
    executorUnknown: '未知',
    stateApplied: '已应用',
    stateApplying: '应用中',
    statePending: '待应用',
    stateApplyFailed: '应用失败',
    stateDegraded: '部分应用',
    stateUnknown: '状态未知',
    errorMessage: '错误信息',
    retryApply: '重试应用',
    retryApplyConfirm: '以当前目标版本重新下发配置？该操作幂等，不会产生重复配置。',
    retrySubmitted: '已重新下发，等待应用结果',
    retryFailed: '重试下发失败',
    routesReadonly: '当前路由（只读）',
    routesReadonlyNote: '原始路由编辑属于受限调试能力，不作为常规页面；请通过模型与接入配置变更。',
    routeModelColumn: '模型',
    routeEndpointColumn: '网关路径',
    routeUpstreamColumn: '上游模型',
    routeProviderColumn: '提供者',
    view: '查看',
    retry: '重试',
    ok: '确定',
    searchPlaceholder: '搜索用户',
    filterStatusAll: '全部',
    userColumn: '用户',
    sessionsEmpty: '暂无登录会话',
    sessionsEmptyHint: '用户登录建立会话后在此显示。',
    sessionsLoadFailed: '登录会话加载失败，请稍后重试。',
    connectionsEmpty: '暂无接入配置',
    connectionsEmptyHint: '新建接入配置后，模型等服务可引用其认证信息。',
    connectionsLoadFailed: '接入配置加载失败，请稍后重试。',
    connectionsSaveFailed: '接入配置保存失败，请稍后重试。',
    connectionsDeleteFailed: '接入配置删除失败，请稍后重试。',
    keyManagedViaRotate: '密钥通过「更新密钥」单独修改，此处不回显原值。',
    disableConnectionNote: '停用后引用该配置的服务将无法获得认证信息；重新启用可恢复。',
    deleteConnectionTitle: '删除接入配置',
    deleteConnectionDescription: '删除后引用该配置的服务调用会失败且无法恢复；请先确认没有对象再引用。',
    confirmDeleteConnection: '确认删除',
    grantFailedRetryHint: '失败的对象已保持选中，可修正后重试。',
    licenseColumn: '授权',
    modelCheckGap: '暂无模型调用检测接口：以下仅展示配置同步状态，保存与应用结果不代表模型实际可调用。',
    statusNoPermission: '无权限查看配置生效详情。',
    consistency: '版本一致性',
    consistencyMatch: '一致',
    consistencyMismatch: '不一致',
    routesEmpty: '暂无网关路由',
    resourceCount: '资源数',
    deliveryModeLabel: '交付方式',
    nameRequired: '请填写名称。',
    serviceRequired: '请填写服务。',
    keyRequired: '请填写新密钥。',
    newKeyPlaceholder: '输入认证信息，只写入服务端',
    revokeFailed: '撤销失败，请稍后重试。',
    affectedModels: '影响模型',
    noReferences: '暂无模型引用',
    referencesUnknownNote: '无模型查看权限或模型列表获取失败时，无法确认引用情况，不按 0 处理。',
    deleteBlockedMessage: '该接入配置仍被以下模型引用；请先在对应模型中更换或解除引用后再删除。',
    deleteReferencesUnverified: '未能获取引用模型信息，无法确认没有模型引用该配置。',
    deploymentSettingsTitle: '部署运行时设置',
    deploymentSettingsDescription: '部署级运行时配置，对当前部署的全部客户端生效。',
    modelGatewayLabel: '模型网关地址',
    modelGatewayDescription: '客户端调用模型使用的 OpenAI 兼容网关基础地址，经服务元数据下发。',
    currentEffectiveValue: '当前生效值',
    overrideValue: '运行时覆盖',
    valueSource: '来源',
    sourceOverride: '运行时覆盖',
    sourceEnv: '环境默认',
    sourceUnset: '未配置',
    noEffectiveValue: '未配置',
    overridePlaceholder: '例如 https://gateway.example.com/v1',
    editOverride: '设置覆盖',
    saveOverride: '保存覆盖',
    clearOverride: '清除覆盖',
    clearOverrideConfirm: '清除后回落为环境变量配置的网关地址，确定清除？',
    effectTimingHint: '保存后无需重启服务：客户端经服务元数据轮询，约 30 秒内自动生效。',
    invalidGatewayUrl: '请输入 http/https 绝对地址（最长 2048 字符）。',
    clusterInternalGatewayUrl: '网关地址不能是集群内域名（*.svc.cluster.local）或单段主机名，客户端将无法访问。',
    deploymentSettingsLoadFailed: '部署设置加载失败，请稍后重试。',
    deploymentSettingsSaveFailed: '部署设置保存失败，请稍后重试。',
    deploymentSettingsRejected: '服务端拒绝了该网关地址',
    deploymentNoPermission: '当前账号无权限查看部署运行时设置。',
    deploymentReadonlyHint: '当前账号仅可查看部署设置，修改需要部署写权限。',
  },
  en: {
    licensesTitle: 'Product license',
    licensesDescription: 'Review license edition, scope, status and validity.',
    importLicenseAction: 'Import license',
    licenseValid: 'Valid',
    licenseRevoked: 'Revoked',
    validUntil: 'Valid until',
    perpetual: 'Perpetual',
    graceUntil: 'Grace until',
    userScope: 'User scope',
    moduleScope: 'Module scope',
    licenseDetail: 'License detail',
    issuedAtLabel: 'Issued at',
    revokeLicenseImpact: 'Revocation disables this license immediately. Make sure a replacement license is in place.',
    licenseImportNote: 'Import validates the signature, deployment binding and validity. A failed import never overwrites the current valid license.',
    sessionsTitle: 'Login sessions',
    sessionsDescription: 'Review valid sign-ins and device information, and revoke when needed. A valid credential does not mean the user is online right now.',
    clientColumn: 'Client / device',
    clientUnknown: 'Unknown',
    lastActive: 'Last activity',
    sessionStateActive: 'Active',
    sessionStateRevoked: 'Revoked',
    revokeLogin: 'Revoke sign-in',
    revokeLoginTitle: 'Revoke this sign-in',
    revokeLoginImpact: 'The client must sign in again after revocation. History records are kept.',
    confirmRevokeLogin: 'Confirm revoke',
    sessionDetail: 'Session detail',
    sessionSubject: 'Subject',
    sessionCreatedAt: 'Created at',
    sessionRevokedAt: 'Revoked at',
    credentialsTitle: 'Connections',
    credentialsDescription: 'Connection and authentication settings for model and other services are maintained and reused here. Secrets are write-only to the server and never echoed back.',
    addConnection: 'New connection',
    serviceColumn: 'Service',
    authColumn: 'Authentication',
    authSet: 'Set, not readable',
    referencedModels: 'Referenced by models',
    connectionCheck: 'Connection check',
    checkUnknown: 'Unknown',
    valueUnknown: 'Unknown',
    notCollected: 'Not collected',
    updateKey: 'Update key',
    updateKeyTitle: 'Update key',
    updateKeyNote: 'The current key is never shown and an empty value never overwrites it. Track application and check results under configuration status after saving.',
    newKey: 'New key',
    configSaved: 'Configuration saved',
    savedNotApplied: 'A successful save only means the configuration is persisted; it is not yet applied or checked.',
    connectionDetail: 'Connection detail',
    usageSubjects: 'Granted to',
    grantAccess: 'Grant',
    rotateRetryNote: 'Rotation failed and the key is unchanged. Fix the input and retry.',
    statusTitle: 'Configuration status',
    statusDescription: 'Desired revision, applied revision and sync results. Save, apply and check are separate stages.',
    desiredRevision: 'Desired revision',
    appliedRevision: 'Applied revision',
    publishedAt: 'Published at',
    configState: 'Configuration state',
    lastSync: 'Last sync',
    executor: 'Applied by',
    executorUnknown: 'Unknown',
    stateApplied: 'Applied',
    stateApplying: 'Applying',
    statePending: 'Pending',
    stateApplyFailed: 'Apply failed',
    stateDegraded: 'Partially applied',
    stateUnknown: 'State unknown',
    errorMessage: 'Error',
    retryApply: 'Retry apply',
    retryApplyConfirm: 'Re-deliver the current desired revision? The operation is idempotent and does not create duplicate configuration.',
    retrySubmitted: 'Re-delivered; waiting for the apply result',
    retryFailed: 'Retry delivery failed',
    routesReadonly: 'Current routes (read-only)',
    routesReadonlyNote: 'Raw route editing is a restricted debugging capability, not a regular page. Change routes through model and connection configuration.',
    routeModelColumn: 'Model',
    routeEndpointColumn: 'Gateway path',
    routeUpstreamColumn: 'Upstream model',
    routeProviderColumn: 'Provider',
    view: 'View',
    retry: 'Retry',
    ok: 'OK',
    searchPlaceholder: 'Search user',
    filterStatusAll: 'All',
    userColumn: 'User',
    sessionsEmpty: 'No login sessions',
    sessionsEmptyHint: 'Sessions appear here after users sign in.',
    sessionsLoadFailed: 'Login sessions failed to load. Try again later.',
    connectionsEmpty: 'No connections',
    connectionsEmptyHint: 'After you create a connection, model and other services can reuse its authentication.',
    connectionsLoadFailed: 'Connections failed to load. Try again later.',
    connectionsSaveFailed: 'Failed to save the connection. Try again later.',
    connectionsDeleteFailed: 'Failed to delete the connection. Try again later.',
    keyManagedViaRotate: 'Keys are changed only through the separate update-key action; the current value is never shown here.',
    disableConnectionNote: 'While disabled, services referencing this connection cannot obtain authentication. Re-enabling restores access.',
    deleteConnectionTitle: 'Delete connection',
    deleteConnectionDescription: 'After deletion, calls from services referencing this connection fail and cannot be recovered. Confirm nothing references it first.',
    confirmDeleteConnection: 'Confirm delete',
    grantFailedRetryHint: 'Failed subjects stay selected so you can fix and retry.',
    licenseColumn: 'License',
    modelCheckGap: 'No model-call check API exists yet: only configuration sync state is shown, and save/apply results do not prove the model is actually callable.',
    statusNoPermission: 'You are not allowed to view configuration status.',
    consistency: 'Revision consistency',
    consistencyMatch: 'In sync',
    consistencyMismatch: 'Out of sync',
    routesEmpty: 'No gateway routes',
    resourceCount: 'Resources',
    deliveryModeLabel: 'Delivery mode',
    nameRequired: 'Enter a name.',
    serviceRequired: 'Enter the service.',
    keyRequired: 'Enter the new key.',
    newKeyPlaceholder: 'Enter the secret; it is only written to the server',
    revokeFailed: 'Revocation failed. Try again later.',
    affectedModels: 'Affected models',
    noReferences: 'No model references',
    referencesUnknownNote: 'Reference counts cannot be confirmed without model-read permission or when the model list fails to load; they are never shown as zero.',
    deleteBlockedMessage: 'This connection is still referenced by the models below. Change or remove the reference on each model first.',
    deleteReferencesUnverified: 'Reference information could not be loaded, so it is unverified that no model references this connection.',
    deploymentSettingsTitle: 'Deployment runtime settings',
    deploymentSettingsDescription: 'Deployment-level runtime configuration applied to every client of this deployment.',
    modelGatewayLabel: 'Model gateway URL',
    modelGatewayDescription: 'Base URL of the OpenAI-compatible model gateway used by clients, distributed through service metadata.',
    currentEffectiveValue: 'Effective value',
    overrideValue: 'Runtime override',
    valueSource: 'Source',
    sourceOverride: 'Runtime override',
    sourceEnv: 'Environment default',
    sourceUnset: 'Not configured',
    noEffectiveValue: 'Not configured',
    overridePlaceholder: 'For example https://gateway.example.com/v1',
    editOverride: 'Set override',
    saveOverride: 'Save override',
    clearOverride: 'Clear override',
    clearOverrideConfirm: 'After clearing, the gateway URL falls back to the environment-configured value. Clear it?',
    effectTimingHint: 'No service restart is needed after saving: clients pick the change up through service-metadata polling within about 30 seconds.',
    invalidGatewayUrl: 'Enter an absolute http or https URL (at most 2048 characters).',
    clusterInternalGatewayUrl: 'The gateway URL must not use a cluster-internal hostname (*.svc.cluster.local) or a single-label hostname; clients could not reach it.',
    deploymentSettingsLoadFailed: 'Deployment settings failed to load. Try again later.',
    deploymentSettingsSaveFailed: 'Deployment settings could not be saved. Try again later.',
    deploymentSettingsRejected: 'The server rejected this gateway URL',
    deploymentNoPermission: 'Your account cannot view deployment runtime settings.',
    deploymentReadonlyHint: 'Your account is read-only here; changing these settings requires the deployment write permission.',
  },
} as const;
export const operationsCopy = copy.zh;
export type OperationsCopyKey = keyof (typeof copy)['zh'];
export function getOperationsCopy(language: keyof typeof copy) {
  return copy[language];
}
