// Page copy for the users / teams / roles / skills work areas. Kept out of
// i18n.ts (owned by the shell) so the main controller can merge these entries
// when the shared dictionary is ready.
const copy = {
  zh: {
    pageUsers: '用户列表',
    pageUsersDescription: '管理企业成员的账号、团队和访问权限。',
    pageTeams: '团队管理',
    pageTeamsDescription: '维护团队成员和共享资源权限。',
    pageRoles: '角色权限',
    pageRolesDescription: '角色定义可执行的管理动作。',
    pageSkills: '技能管理',
    pageSkillsDescription: '管理可复用能力、版本、权限和引用。',
    pageAssignments: '技能授权',
    pageAssignmentsDescription: '维护技能的使用授权，用户详情可反向查看同一份关系。',
    searchUserPlaceholder: '搜索姓名或账号',
    searchTeamPlaceholder: '搜索团队名称',
    searchRolePlaceholder: '搜索角色',
    searchSkillPlaceholder: '搜索名称或用途',
    allTeams: '全部团队',
    allRoles: '全部角色',
    allStatus: '全部状态',
    nameAndAccount: '姓名 / 账号',
    belongTeams: '所属团队',
    accountRoles: '角色',
    sourceColumn: '来源',
    lastLogin: '最近登录',
    sourceUnknown: '来源未知',
    valueUnknown: '未知',
    notCollected: '暂未统计',
    noTeams: '未加入团队',
    noRoles: '未分配角色',
    view: '查看',
    moreActions: '更多',
    statusEnabled: '已启用',
    statusDisabled: '已停用',
    disableUserTitle: '停用用户',
    disableUserImpact: '停用后阻止新登录与令牌续期；已有会话的撤销结果以登录会话列表为准，受保护请求在服务端校验。',
    disableSelfWarning: '该账号正用于当前控制台，停用后你将同时被注销。',
    disableUserActiveSessions: '当前有效登录会话',
    disableUserSessionsUnknown: '活动登录暂无法获取',
    disableUserOwnershipNote: '如该用户仍负责数字员工，请先完成负责人交接再停用。',
    confirmDisableUser: '确认停用',
    detailBasic: '基本信息',
    detailOrg: '团队与角色',
    detailAccess: '访问权限',
    detailLinks: '关联账号',
    detailSessions: '登录会话',
    emailUnset: '未设置',
    accountType: '账号类型',
    createdAtLabel: '创建时间',
    updatedAtLabel: '更新时间',
    adjustOrg: '调整团队与角色',
    adjustOrgTitle: '调整团队与角色',
    adjustOrgNote: '修改团队可能改变继承权限，保存前请核对资源影响。',
    accessResource: '资源',
    accessPermission: '权限',
    accessSource: '来源',
    accessState: '有效状态',
    accessDirect: '直接授权',
    accessViaRole: '角色',
    accessViaTeam: '团队',
    accessUse: '使用',
    accessEffective: '有效',
    accessResourceDisabled: '资源已停用',
    accessUserDisabled: '账号已停用',
    accessNote: '继承权限请到来源处修改；此处与资源侧维护的是同一份授权关系。',
    accessEmpty: '暂无可展示的资源授权',
    accessEmptyHint: '为该用户、其角色或团队授权技能与模型后在此展示。',
    resourceTypeSkill: '技能',
    resourceTypeModel: '模型',
    linksLoadFailed: '关联账号加载失败',
    linksEmpty: '暂无关联账号',
    linksEmptyHint: '在账号关联页将外部平台账号绑定到该用户后在此展示。',
    linksNoPermission: '当前账号没有查看账号关联的权限。',
    linkSource: '来源平台',
    linkExternal: '外部账号',
    unlinkAction: '解除关联',
    unlinkTitle: '解除账号关联',
    unlinkImpact: '解除后无法通过该关联识别企业成员，企业数据访问将被拒绝；平台账号与已有资料不删除。',
    confirmUnlink: '确认解除',
    sessionsNote: '有效登录凭证不等于此刻在线。',
    sessionClient: '客户端 / 设备',
    sessionLastActive: '最近活动',
    sessionStateActive: '有效',
    sessionStateRevoked: '已撤销',
    revokeLogin: '撤销登录',
    revokeLoginTitle: '撤销本次登录',
    revokeLoginImpact: '撤销后该客户端需要重新登录；不删除历史操作记录。',
    confirmRevokeLogin: '确认撤销',
    sessionsEmpty: '暂无登录会话',
    sessionsEmptyHint: '该用户当前没有有效或历史登录会话。',
    sessionsLoadFailed: '登录会话加载失败',
    sessionDetail: '会话详情',
    sessionSubject: '主题',
    sessionCreatedAt: '创建时间',
    sessionRevokedAt: '撤销时间',
    memberCount: '成员数',
    teamMembersTab: '成员',
    teamAccessTab: '资源权限',
    teamAccessNote: '成员通过本团队继承以下资源使用权限。',
    rolePermissionsTab: '权限项',
    roleSubjectsTab: '授予对象',
    permissionCount: '权限项',
    roleMemberCount: '成员数',
    roleSubjectsEmpty: '暂无授予对象',
    skillPurpose: '用途',
    skillEmployees: '关联数字员工',
    skillDetailConfig: '说明与配置',
    skillDetailVersions: '版本记录',
    skillDetailAccess: '使用权限',
    skillDetailEmployees: '关联数字员工',
    skillEmployeesEmpty: '暂未统计',
    skillEmployeesEmptyHint: '当前接口不提供技能与数字员工的关联关系。',
    skillDeleteBlockedTitle: '无法删除被引用的技能',
    skillDeleteBlockedNote: '该技能仍有使用授权。请先在“使用权限”中撤销全部授权，再删除技能。',
    skillDeleteUncheckedNote: '当前接口不提供数字员工对技能的引用关系；删除前请确认没有数字员工仍在使用该技能。',
    versionSha: 'SHA256',
    skillAccessEmpty: '暂无使用授权',
    skillAccessEmptyHint: '授权用户、角色或团队使用该技能后在此展示。',
    grantAccess: '调整授权',
    versionSize: '大小',
    versionCreatedAt: '创建时间',
    publishAction: '发布',
    withdrawAction: '撤回',
    retry: '重试',
    ok: '确定',
    importResultTitle: '导入结果',
    userImportPartial: '部分行未导入，失败行与原因如下。',
    deleteSkillConfirm: '确认删除技能',
    stopSkillFirst: '停用后相关能力对已授权对象不可用。',
    disableResultTitle: '停用结果',
    disableAccountDone: '账号已停用',
    disableSessionsRevoked: '已撤销有效会话',
    disableSessionsFailed: '部分会话撤销失败，请到登录会话页处理。',
    disableSessionsNone: '没有需要撤销的有效会话。',
    disableSessionsUnknown: '账号已停用，但暂无法获取会话撤销结果，请到登录会话页重试。',
    accessSkillsUnknown: '技能授权范围暂无法获取',
    accessModelsUnknown: '模型授权范围暂无法获取',
    accessStateUnknown: '授权状态未知',
    disableSessionsNoPermission: '当前账号没有撤销会话的权限，请到登录会话页处理。',
    disableBoundaryNote: '数字员工负责人依赖无法通过当前接口确认；新登录与令牌续期由服务端阻止，已签发的令牌可能存在短暂失效窗口。',
    assignmentSubject: '授权对象',
    assignmentRevoke: '撤销授权',
  },
  en: {
    pageUsers: 'Users',
    pageUsersDescription: 'Manage enterprise member accounts, teams and access.',
    pageTeams: 'Teams',
    pageTeamsDescription: 'Maintain team membership and shared resource access.',
    pageRoles: 'Roles',
    pageRolesDescription: 'Roles define the management actions members can take.',
    pageSkills: 'Skills',
    pageSkillsDescription: 'Manage reusable capabilities, versions, access and references.',
    pageAssignments: 'Skill grants',
    pageAssignmentsDescription: 'Maintain skill usage grants; the user detail shows the same relationship in reverse.',
    searchUserPlaceholder: 'Search name or account',
    searchTeamPlaceholder: 'Search team name',
    searchRolePlaceholder: 'Search role',
    searchSkillPlaceholder: 'Search name or purpose',
    allTeams: 'All teams',
    allRoles: 'All roles',
    allStatus: 'All statuses',
    nameAndAccount: 'Name / account',
    belongTeams: 'Teams',
    accountRoles: 'Roles',
    sourceColumn: 'Source',
    lastLogin: 'Last sign-in',
    sourceUnknown: 'Source unknown',
    valueUnknown: 'Unknown',
    notCollected: 'Not collected',
    noTeams: 'No team',
    noRoles: 'No role',
    view: 'View',
    moreActions: 'More',
    statusEnabled: 'Enabled',
    statusDisabled: 'Disabled',
    disableUserTitle: 'Disable user',
    disableUserImpact: 'Disabling blocks new sign-ins and token renewal; revocation of existing sessions is reported in the login sessions list and enforced server-side.',
    disableSelfWarning: 'This account is signed in to the current console. Disabling it signs you out as well.',
    disableUserActiveSessions: 'Current active login sessions',
    disableUserSessionsUnknown: 'Active sign-ins unavailable',
    disableUserOwnershipNote: 'If this user owns digital employees, hand over ownership before disabling.',
    confirmDisableUser: 'Confirm disable',
    detailBasic: 'Basic info',
    detailOrg: 'Teams & roles',
    detailAccess: 'Access',
    detailLinks: 'Linked accounts',
    detailSessions: 'Login sessions',
    emailUnset: 'Not set',
    accountType: 'Account type',
    createdAtLabel: 'Created at',
    updatedAtLabel: 'Updated at',
    adjustOrg: 'Edit teams & roles',
    adjustOrgTitle: 'Edit teams & roles',
    adjustOrgNote: 'Changing teams may change inherited access. Review the impact before saving.',
    accessResource: 'Resource',
    accessPermission: 'Permission',
    accessSource: 'Source',
    accessState: 'Effective state',
    accessDirect: 'Direct grant',
    accessViaRole: 'Role',
    accessViaTeam: 'Team',
    accessUse: 'Use',
    accessEffective: 'Effective',
    accessResourceDisabled: 'Resource disabled',
    accessUserDisabled: 'Account disabled',
    accessNote: 'Edit inherited access at its source; this is the same grant relationship maintained from the resource side.',
    accessEmpty: 'No resource grants to show',
    accessEmptyHint: 'Grant skills or models to this user, their roles or teams to see them here.',
    resourceTypeSkill: 'Skill',
    resourceTypeModel: 'Model',
    linksLoadFailed: 'Linked accounts failed to load',
    linksEmpty: 'No linked accounts',
    linksEmptyHint: 'Link an external platform account to this user on the account mappings page.',
    linksNoPermission: 'Your account cannot view linked accounts.',
    linkSource: 'Platform',
    linkExternal: 'External account',
    unlinkAction: 'Unlink',
    unlinkTitle: 'Unlink account',
    unlinkImpact: 'After unlinking, this mapping no longer identifies an enterprise member and enterprise data access is rejected. The platform account and existing data are kept.',
    confirmUnlink: 'Confirm unlink',
    sessionsNote: 'A valid credential does not mean the user is online right now.',
    sessionClient: 'Client / device',
    sessionLastActive: 'Last activity',
    sessionStateActive: 'Active',
    sessionStateRevoked: 'Revoked',
    revokeLogin: 'Revoke sign-in',
    revokeLoginTitle: 'Revoke this sign-in',
    revokeLoginImpact: 'The client must sign in again after revocation. History records are kept.',
    confirmRevokeLogin: 'Confirm revoke',
    sessionsEmpty: 'No login sessions',
    sessionsEmptyHint: 'This user has no active or past login sessions.',
    sessionsLoadFailed: 'Login sessions failed to load',
    sessionDetail: 'Session detail',
    sessionSubject: 'Subject',
    sessionCreatedAt: 'Created at',
    sessionRevokedAt: 'Revoked at',
    memberCount: 'Members',
    teamMembersTab: 'Members',
    teamAccessTab: 'Resource access',
    teamAccessNote: 'Members inherit the following resource access through this team.',
    rolePermissionsTab: 'Permissions',
    roleSubjectsTab: 'Granted to',
    permissionCount: 'Permissions',
    roleMemberCount: 'Members',
    roleSubjectsEmpty: 'No grantees',
    skillPurpose: 'Purpose',
    skillEmployees: 'Linked digital employees',
    skillDetailConfig: 'Configuration',
    skillDetailVersions: 'Versions',
    skillDetailAccess: 'Access',
    skillDetailEmployees: 'Digital employees',
    skillEmployeesEmpty: 'Not collected',
    skillEmployeesEmptyHint: 'The current API does not expose skill-to-employee references.',
    skillDeleteBlockedTitle: 'Skill still referenced',
    skillDeleteBlockedNote: 'This skill still has usage grants. Revoke all grants under "Access" before deleting it.',
    skillDeleteUncheckedNote: 'The API does not expose digital-employee references to this skill. Make sure no digital employee still uses it before deleting.',
    versionSha: 'SHA256',
    skillAccessEmpty: 'No usage grants',
    skillAccessEmptyHint: 'Grant this skill to users, roles or teams to see them here.',
    grantAccess: 'Edit grants',
    versionSize: 'Size',
    versionCreatedAt: 'Created at',
    publishAction: 'Publish',
    withdrawAction: 'Withdraw',
    retry: 'Retry',
    ok: 'OK',
    importResultTitle: 'Import result',
    userImportPartial: 'Some rows were not imported. Failed rows and reasons are listed below.',
    deleteSkillConfirm: 'Confirm skill deletion',
    stopSkillFirst: 'After disabling, the capability is unavailable to granted subjects.',
    disableResultTitle: 'Disable result',
    disableAccountDone: 'Account disabled',
    disableSessionsRevoked: 'Active sessions revoked',
    disableSessionsFailed: 'Some sessions could not be revoked. Handle them on the login sessions page.',
    disableSessionsNone: 'No active sessions to revoke.',
    disableSessionsUnknown: 'Account disabled, but session revocation results are unavailable. Retry on the login sessions page.',
    accessSkillsUnknown: 'Skill grants are unavailable',
    accessModelsUnknown: 'Model grants are unavailable',
    accessStateUnknown: 'Access status unknown',
    disableSessionsNoPermission: 'Your account cannot revoke sessions. Handle them on the login sessions page.',
    disableBoundaryNote: 'Digital-employee ownership cannot be checked with the current API. New sign-ins and token renewal are blocked server-side; already-issued tokens may take a short window to expire.',
    assignmentSubject: 'Subject',
    assignmentRevoke: 'Revoke grant',
  },
} as const;
export const resourcesCopy = copy.zh;
export type ResourcesCopyKey = keyof (typeof copy)['zh'];
export function getResourcesCopy(language: keyof typeof copy) {
  return copy[language];
}
