// Service-status module copy (ServicesView, MemoryView, KnowledgeView).
// `src/admin/i18n.ts` is frozen for this work package, so every string the
// antd rewrite introduces lives here in both languages. The main controller
// can merge `servicesCopy` into the shared dictionary later; components read
// it through `servicesT`.

import type { AdminLanguage } from './i18n.js';

const zh = {
  servicesTitle: '服务状态',
  servicesDescription: '按业务影响查看检测结果；服务连通不能替代调用、处理或写入成功。',
  servicesColService: '服务',
  servicesColResult: '检测结果',
  servicesColImpact: '业务影响',
  servicesColLastCheck: '最后检测',
  servicesColActions: '操作',
  servicesRecheck: '重新检测',
  servicesDetail: '查看详情',
  servicesResultOk: '正常',
  servicesResultBad: '连接失败',
  servicesResultFailed: '检测失败',
  servicesNoProbe: '暂无检测接口',
  svcMemory: '长期记忆',
  svcKnowledge: '知识检索',
  svcRuntime: '数字员工运行服务',
  svcGateway: '模型网关',
  impactMemoryOk: '记忆读写与检索服务可连接',
  impactMemoryBad: '记忆读写与检索暂不可用',
  impactKnowledgeOk: '知识检索服务可连接',
  impactKnowledgeBad: '资料检索暂不可用',
  impactNoProbe: '未接入健康检测接口，暂无法按业务影响判断',
  memoryTechnicalTitle: '技术详情（运维可见）',
  knowledgeTechnicalTitle: '技术详情（运维可见）',
  labelServer: '服务地址',
  labelAccount: '平台账户',
  labelAccountCount: '账户数',
  labelEmployeeCount: '员工记忆数',
  labelServiceUrl: '服务地址',
  labelKnowledgeCount: '知识库数',
  labelCheckedAt: '检测时间',
  memoryTitle: '长期记忆',
  memoryScopedDescription: '查看该数字员工长期记忆的归属与已有统计。',
  memoryFactScope: '记忆归属',
  memoryFactSessions: '会话数',
  memoryFactLastActive: '最近活动',
  memoryFactLastWrite: '最近记忆写入',
  memoryLastWriteUnknown: '暂未采集',
  memoryNotProvisioned: '该员工暂无记忆指标（未在记忆服务中返回），不以 0 代替',
  memorySessionsNote: '会话数不是记忆条数；启停后的读写与保留行为确认前，不开放编辑开关。',
  memoryAccountsTitle: '平台账户',
  memoryEmployeesTitle: '员工记忆统计',
  memoryColAccount: '账户',
  memoryColUserCount: '用户数',
  memoryColEmployee: '数字员工',
  memoryColMemoryUser: '记忆用户',
  memoryColSessions: '会话数',
  memoryColLastActive: '最近活动',
  memoryNoAccounts: '暂无账户',
  memoryServiceStatusHint: '连接与检测归「系统管理 → 服务状态」；此处为业务统计。',
  knowledgeTitle: '知识库',
  knowledgeDescription: '维护资料内容、使用范围与数字员工关联。',
  knowledgeColName: '知识库',
  knowledgeColDescription: '说明',
  knowledgeColDocs: '文档数',
  knowledgeColProcessState: '处理状态',
  knowledgeColScope: '使用范围',
  knowledgeColUpdatedAt: '更新时间',
  knowledgeColActions: '操作',
  knowledgeNotCounted: '暂未统计',
  knowledgeScopeUnknown: '未提供',
  knowledgeProcessStateHint: '文档处理状态需知识系统任务接口；服务连通不代表全部处理完成。',
  knowledgeManageDocs: '管理文档',
  knowledgeDocsNote:
    '打开外部知识系统的管理页面：可能需要知识系统账号单独登录，能否查看或编辑文档以知识系统内的权限为准；链接不携带密钥。',
  knowledgeDocsInvalid: '服务地址为空或不是 http/https 链接，暂不提供管理入口；请联系部署侧修正知识服务地址。',
  knowledgeUnconfiguredTitle: '知识库服务尚未配置',
  knowledgeUnconfiguredHint: '请联系系统管理员在部署侧完成知识服务配置；配置后此处展示知识库清单。',
  knowledgeUnhealthyTitle: '知识库服务连接失败',
  knowledgeRetry: '重试',
  knowledgeForbiddenTitle: '无权限查看知识库状态',
  knowledgeForbiddenHint: '当前账号无权访问知识库服务摘要；不展示对象内容。',
  knowledgeEmptyTitle: '尚未创建知识库',
  knowledgeEmptyHint: '在知识系统中创建后，此处自动展示并可与数字员工关联。',
  knowledgeExternalTitle: '受控文档管理交接',
  notProvided: '未提供',
} as const;

const en: Record<keyof typeof zh, string> = {
  servicesTitle: 'Service status',
  servicesDescription:
    'Detection results by business impact; reachability does not imply invocation, processing, or write success.',
  servicesColService: 'Service',
  servicesColResult: 'Result',
  servicesColImpact: 'Business impact',
  servicesColLastCheck: 'Last check',
  servicesColActions: 'Actions',
  servicesRecheck: 'Check again',
  servicesDetail: 'Details',
  servicesResultOk: 'Healthy',
  servicesResultBad: 'Unreachable',
  servicesResultFailed: 'Check failed',
  servicesNoProbe: 'No probe API',
  svcMemory: 'Long-term memory',
  svcKnowledge: 'Knowledge retrieval',
  svcRuntime: 'Digital-employee runtime',
  svcGateway: 'Model gateway',
  impactMemoryOk: 'Memory read/write and retrieval reachable',
  impactMemoryBad: 'Memory read/write and retrieval unavailable',
  impactKnowledgeOk: 'Knowledge retrieval reachable',
  impactKnowledgeBad: 'Document retrieval unavailable',
  impactNoProbe: 'No health-probe API wired yet; business impact cannot be judged',
  memoryTechnicalTitle: 'Technical details (ops)',
  knowledgeTechnicalTitle: 'Technical details (ops)',
  labelServer: 'Server',
  labelAccount: 'Platform account',
  labelAccountCount: 'Accounts',
  labelEmployeeCount: 'Employee memories',
  labelServiceUrl: 'Service URL',
  labelKnowledgeCount: 'Knowledge bases',
  labelCheckedAt: 'Checked',
  memoryTitle: 'Long-term memory',
  memoryScopedDescription: 'Ownership and collected statistics for this digital employee.',
  memoryFactScope: 'Memory scope',
  memoryFactSessions: 'Sessions',
  memoryFactLastActive: 'Last activity',
  memoryFactLastWrite: 'Last memory write',
  memoryLastWriteUnknown: 'Not collected',
  memoryNotProvisioned: 'No memory metrics for this employee (absent from the memory service); not reported as 0',
  memorySessionsNote:
    'Session count is not memory count; no edit switch until read/write and retention semantics after toggling are confirmed.',
  memoryAccountsTitle: 'Platform accounts',
  memoryEmployeesTitle: 'Employee memory statistics',
  memoryColAccount: 'Account',
  memoryColUserCount: 'Users',
  memoryColEmployee: 'Digital employee',
  memoryColMemoryUser: 'Memory user',
  memoryColSessions: 'Sessions',
  memoryColLastActive: 'Last activity',
  memoryNoAccounts: 'No accounts',
  memoryServiceStatusHint:
    'Connectivity and detection live under "System → Service status"; this view is business statistics.',
  knowledgeTitle: 'Knowledge bases',
  knowledgeDescription: 'Maintain content, audience, and digital-employee associations.',
  knowledgeColName: 'Knowledge base',
  knowledgeColDescription: 'Description',
  knowledgeColDocs: 'Documents',
  knowledgeColProcessState: 'Processing',
  knowledgeColScope: 'Audience',
  knowledgeColUpdatedAt: 'Updated',
  knowledgeColActions: 'Actions',
  knowledgeNotCounted: 'Not counted yet',
  knowledgeScopeUnknown: 'Not provided',
  knowledgeProcessStateHint:
    'Document processing needs the knowledge system task API; reachability does not mean everything is processed.',
  knowledgeManageDocs: 'Manage documents',
  knowledgeDocsNote:
    "Opens the external knowledge system console: it may require a separate sign-in, and what you can view or edit there follows that system's own permissions; the link carries no secrets.",
  knowledgeDocsInvalid:
    'The service URL is empty or not an http/https link; no management entry is offered. Ask the deployment side to fix the knowledge service URL.',
  knowledgeUnconfiguredTitle: 'Knowledge service not configured',
  knowledgeUnconfiguredHint:
    'Ask an administrator to configure the knowledge service at deployment level; bases appear here afterwards.',
  knowledgeUnhealthyTitle: 'Knowledge service unreachable',
  knowledgeRetry: 'Retry',
  knowledgeForbiddenTitle: 'No permission to view knowledge status',
  knowledgeForbiddenHint: 'This account cannot access the knowledge service summary; object content is not shown.',
  knowledgeEmptyTitle: 'No knowledge bases yet',
  knowledgeEmptyHint: 'Create one in the knowledge system; it appears here and can be linked to digital employees.',
  knowledgeExternalTitle: 'Controlled document-management handoff',
  notProvided: 'Not provided',
};

export const servicesCopy: Record<AdminLanguage, Record<keyof typeof zh, string>> = { zh, en };

export type ServicesCopyKey = keyof typeof zh;

export function servicesT(key: ServicesCopyKey, language: AdminLanguage = 'zh'): string {
  return servicesCopy[language][key];
}
