const copy = {
  zh: {
    brand: "知远企业管理后台",
    brandShort: "知远",
    admin: "企业管理后台",
    enterprise: "当前企业",
    navigation: "主导航",
    overview: "概览",
    employees: "数字员工",
    knowledge: "知识库",
    skills: "技能管理",
    users: "用户管理",
    audit: "日志审计",
    system: "系统管理",
    userList: "用户列表",
    teams: "团队管理",
    roles: "角色权限",
    accounts: "账号关联",
    sessions: "登录会话",
    models: "模型服务",
    connections: "接入配置",
    modelList: "模型列表",
    channels: "渠道接入",
    channelHint:
      "查看数字员工已接入的渠道。渠道配置由部署管理员维护，当前接口不支持在此修改。",
    channelName: "渠道名称",
    channelStatus: "接入状态",
    configured: "已配置",
    channelScope: "此页仅反映配置记录；不代表消息收发已验证。",
    channelFailure: "渠道信息暂无法获取，请刷新重试。",
    services: "服务状态",
    configuration: "配置生效详情",
    settings: "基本设置",
    licenses: "产品授权",
    signIn: "登录企业管理后台",
    signInHint: "使用企业账号登录，按已获权限管理用户、数字员工和服务。",
    signOut: "退出登录",
    switchAccount: "切换账号",
    forbidden: "没有管理权限",
    notFound: "页面不存在",
    theme: "外观",
    systemTheme: "跟随系统",
    light: "浅色",
    dark: "深色",
    accountScope: "仅展示当前账号可访问的管理入口",
    settingsHint:
      "企业资料由部署配置维护。当前接口尚不支持在此修改；外观设置可通过右上角切换。",
    overviewHint: "查看当前可管理的资源，进入业务页面处理工作。",
    accountCount: "平台账号",
    unknown: "暂无法获取",
    manage: "进入管理",
    quickLinks: "常用入口",
    runningSummary: "数字员工运行概况",
    visibleEmployees: "可管理数字员工",
    readyEmployees: "部署就绪",
    pendingRequests: "待审批申请",
    pendingWork: "待处理事项",
    reviewRequests: "查看申请审批",
    runSummaryHint:
      "仅统计当前账号可见范围。部署就绪不代表模型调用和渠道收发已验证。",
    recentActivity: "最近操作",
    countHint: "平台账号包含接口返回的全部账号，不代表企业成员数或在线人数。",
    auditFailed: "最近操作暂无法获取，请刷新重试。",
    auditRestricted: "当前账号无日志查看权限。",
    event: "操作",
    actor: "操作人",
    result: "结果",
    overviewFailed: "部分概览数据暂无法获取，请刷新重试。",
  },
  en: {
    brand: "Zhiyuan Enterprise Administration",
    brandShort: "Zhiyuan",
    admin: "Administration",
    enterprise: "Current enterprise",
    navigation: "Main navigation",
    overview: "Overview",
    employees: "Digital employees",
    knowledge: "Knowledge",
    skills: "Skills",
    users: "Users",
    audit: "Audit logs",
    system: "System",
    userList: "Users",
    teams: "Teams",
    roles: "Roles",
    accounts: "Account mappings",
    sessions: "Login sessions",
    models: "Model services",
    connections: "Connections",
    modelList: "Model catalog",
    channels: "Channels",
    channelHint:
      "View employee channel connections. Deployment administrators maintain configuration; this API does not support editing it here.",
    channelName: "Channel name",
    channelStatus: "Configuration status",
    configured: "Configured",
    channelScope:
      "Configuration records do not prove successful message delivery.",
    channelFailure: "Channel information is unavailable. Refresh to retry.",
    services: "Service health",
    configuration: "Configuration status",
    settings: "Settings",
    licenses: "License",
    signIn: "Sign in to enterprise administration",
    signInHint:
      "Manage users, digital employees and services with your authorized enterprise account.",
    signOut: "Sign out",
    switchAccount: "Switch account",
    forbidden: "Access denied",
    notFound: "Page not found",
    theme: "Appearance",
    systemTheme: "System",
    light: "Light",
    dark: "Dark",
    accountScope: "Only authorized destinations are shown",
    settingsHint:
      "Enterprise information is managed by deployment configuration. This API does not support editing it here. Change appearance at the top right.",
    overviewHint: "View manageable resources and open the relevant work area.",
    accountCount: "Platform accounts",
    unknown: "Unavailable",
    manage: "Manage",
    quickLinks: "Quick links",
    runningSummary: "Digital employee runtime",
    visibleEmployees: "Manageable employees",
    readyEmployees: "Deployment ready",
    pendingRequests: "Pending approvals",
    pendingWork: "Pending work",
    reviewRequests: "Review requests",
    runSummaryHint:
      "Counts are scoped to your account. Deployment readiness does not verify model calls or channel delivery.",
    recentActivity: "Recent activity",
    countHint:
      "Account totals include all accounts returned by the API, not enterprise members or online users.",
    auditFailed: "Recent activity is unavailable. Refresh to retry.",
    auditRestricted: "Your account cannot read audit logs.",
    event: "Action",
    actor: "Actor",
    result: "Result",
    overviewFailed: "Some overview metrics are unavailable. Refresh to retry.",
  },
};
export const shellCopy = copy.zh;
export function getShellCopy(language: keyof typeof copy) {
  return copy[language];
}
