// Employee workbench copy (普通员工使用入口). `src/admin/i18n.ts` is frozen
// for this work package, so every string the workbench introduces lives
// here in both languages, read through `workbenchT`.

import type { AdminLanguage } from './i18n.js';

const zh = {
  brand: '员工工作台',
  title: '我的工作台',
  desc: '使用已获授权的数字员工，或查看自己的申请。',
  switchToAdmin: '管理后台',
  switchToWorkbench: '工作台',
  colEmployee: '数字员工',
  colPurpose: '用途',
  colAccess: '权限来源',
  colStatus: '状态',
  colAction: '操作',
  actionStart: '开始使用',
  startUnavailable: '员工尚未发布完成，暂时不能使用。',
  startSleeping: '该员工当前休眠，开始使用时会自动唤醒（可能需要十几秒）。',
  rosterEmpty: '还没有可用的数字员工。可以申请一个，或联系管理员授权。',
  rosterFailed: '数字员工列表加载失败。',
  purposeMissing: '未填写',
  accessOwner: '我是负责人',
  accessAdmin: '管理员',
  accessAll: '全体成员',
  accessTeam: '团队',
  accessUser: '指定人员',
  accessLegacyTeam: '部门成员',
  accessUnknown: '可见范围未标注',
  myRequestsTitle: '我的申请',
  myRequestsEmpty: '暂无申请记录。',
  myRequestsViewAll: '查看全部',
  actionApply: '申请数字员工',
  actionMyRequests: '我的申请',
  quotaLabel: '申请名额',
  quotaHint: '审批中的申请也占用名额。',
  sessionExpired: '登录状态已过期，请重新登录后再操作。',
  signInAgain: '重新登录',
  phaseReady: '已发布',
  phasePending: '部署中',
  phaseSleeping: '休眠中',
  phaseError: '部署失败',
  phaseUnknown: '未知',

  applyTitle: '申请数字员工',
  applyDesc: '说明用途和服务对象，由审批人确认。',
  labelSlug: '技术标识',
  slugExtra: '小写字母、数字与连字符，用于地址与命令行，创建后不可更改。',
  slugRequired: '请输入技术标识。',
  labelName: '申请名称',
  nameRequired: '请输入申请名称。',
  labelPurpose: '使用目的',
  purposePlaceholder: '这个数字员工做什么、给谁用（必填，500 字内）',
  purposeRequired: '请填写使用目的。',
  labelTeam: '所属团队',
  teamPlaceholder: '选择团队（必选）',
  teamRequired: '请选择所属团队。',
  teamMissing: '当前账号未加入任何团队，请联系管理员加入团队后再申请。',
  labelScope: '期望服务对象',
  scopeSelf: '仅我本人',
  scopeTeam: '我的团队',
  scopeAll: '全体成员',
  scopeAllHint: '全员开放需要管理员审批后生效。',
  scopeRequired: '请选择期望服务对象。',
  labelNote: '补充说明',
  notePlaceholder: '给审批人的补充信息（可选，500 字内）',
  defaultModelNote: '平台默认模型',
  submitApply: '提交申请',
  applyPolicyAdminOnly: '当前平台仅允许管理员创建数字员工，暂不能自助申请。',
  applyQuotaFull: '申请名额已用完（审批中的申请也占用名额），无法再提交。',
  applyFailed: '申请提交失败，请稍后重试。',
  applyLoadFailed: '申请信息加载失败，请返回后重试。',
  createdNotice: '已创建并开始部署。',
  violationsTitle: '请修正以下问题：',
  fieldModels: '平台默认模型',

  submittedTitle: '申请已提交',
  submittedDesc: '可以在我的申请中查看进展。',
  timelineSubmitted: '已提交',
  timelineAwaiting: '待审批',
  timelineAwaitingDesc: '待平台管理员审批',
  timelineDeploy: '待部署',
  timelineDeployDesc: '获批后自动部署，结果单独反馈。',
  viewRequest: '查看申请',
  backToWorkbench: '返回工作台',

  requestsTitle: '我的申请',
  requestsDesc: '仅展示当前用户提交的申请。',
  colReqName: '名称',
  colReqTime: '提交时间',
  colReqApproval: '审批状态',
  colReqDeploy: '部署状态',
  colReqAction: '操作',
  actionView: '查看',
  reqStatePending: '待审批',
  reqStateApproved: '已通过',
  reqStateRejected: '已驳回',
  reqStateDeployed: '已创建',
  reqStateUnknown: '未知状态',
  deployNotStarted: '尚未开始',
  deployRejected: '未部署',
  deployGone: '部署记录已不存在',
  deployUnknown: '未知',
  filterAll: '全部',
  requestsEmpty: '暂无申请记录。',
  requestsFailed: '申请列表加载失败。',
  detailFailed: '申请详情加载失败。',
  detailNotFound: '申请不存在或无权查看。',
  detailTitle: '申请详情',
  detailApplicant: '申请人',
  detailTeam: '所属团队',
  detailPurpose: '用途',
  detailNote: '补充说明',
  detailModel: '使用模型',
  detailApproval: '审批结果',
  detailDeploy: '部署结果',
  detailRejectedReason: '驳回原因',
  timelineDecidedBy: '审批人',
  backToRequests: '返回申请列表',
  notProvided: '—',
};

const en: Record<keyof typeof zh, string> = {
  brand: 'Employee workbench',
  title: 'My workbench',
  desc: 'Use the digital employees you are authorized for, or track your own requests.',
  switchToAdmin: 'Admin console',
  switchToWorkbench: 'Workbench',
  colEmployee: 'Digital employee',
  colPurpose: 'Purpose',
  colAccess: 'Access via',
  colStatus: 'Status',
  colAction: 'Actions',
  actionStart: 'Start',
  startUnavailable: 'This employee is not published yet and cannot be used.',
  startSleeping: 'This employee is hibernating; starting will wake it up (may take a moment).',
  rosterEmpty: 'No digital employees are available yet. Apply for one, or ask an administrator for access.',
  rosterFailed: 'Failed to load the digital employee list.',
  purposeMissing: 'Not provided',
  accessOwner: 'Owner',
  accessAdmin: 'Administrator',
  accessAll: 'Everyone',
  accessTeam: 'Team',
  accessUser: 'Named user',
  accessLegacyTeam: 'Department member',
  accessUnknown: 'Scope not labeled',
  myRequestsTitle: 'My requests',
  myRequestsEmpty: 'No requests yet.',
  myRequestsViewAll: 'View all',
  actionApply: 'Apply for a digital employee',
  actionMyRequests: 'My requests',
  quotaLabel: 'Request quota',
  quotaHint: 'Pending requests count against the quota.',
  sessionExpired: 'Your session has expired. Sign in again to continue.',
  signInAgain: 'Sign in again',
  phaseReady: 'Published',
  phasePending: 'Deploying',
  phaseSleeping: 'Hibernating',
  phaseError: 'Deployment failed',
  phaseUnknown: 'Unknown',

  applyTitle: 'Apply for a digital employee',
  applyDesc: 'Describe the purpose and audience; an approver reviews the request.',
  labelSlug: 'System name',
  slugExtra: 'Lowercase letters, digits and hyphens; used in addresses and CLI. Cannot be changed later.',
  slugRequired: 'Enter the system name.',
  labelName: 'Requested name',
  nameRequired: 'Enter the requested name.',
  labelPurpose: 'Purpose',
  purposePlaceholder: 'What this employee does and for whom (required, ≤500 chars)',
  purposeRequired: 'Describe the purpose.',
  labelTeam: 'Owning team',
  teamPlaceholder: 'Select a team (required)',
  teamRequired: 'Select the owning team.',
  teamMissing: 'Your account is not in any team yet. Ask an administrator to add you before applying.',
  labelScope: 'Intended audience',
  scopeSelf: 'Only me',
  scopeTeam: 'My team',
  scopeAll: 'Everyone',
  scopeAllHint: 'Opening to everyone takes effect after an administrator approves.',
  scopeRequired: 'Select the intended audience.',
  labelNote: 'Notes',
  notePlaceholder: 'Anything the approver should know (optional, ≤500 chars)',
  defaultModelNote: 'Platform default model',
  submitApply: 'Submit request',
  applyPolicyAdminOnly:
    'Only administrators may create digital employees on this platform; self-service requests are disabled.',
  applyQuotaFull: 'Your request quota is used up (pending requests count too), so no further request can be submitted.',
  applyFailed: 'Submitting the request failed. Try again later.',
  applyLoadFailed: 'Failed to load your request profile. Go back and retry.',
  createdNotice: 'Created and now deploying.',
  violationsTitle: 'Fix the following problems:',
  fieldModels: 'Platform default model',

  submittedTitle: 'Request submitted',
  submittedDesc: 'Track its progress under My requests.',
  timelineSubmitted: 'Submitted',
  timelineAwaiting: 'Awaiting approval',
  timelineAwaitingDesc: 'A platform administrator will review it',
  timelineDeploy: 'Awaiting deployment',
  timelineDeployDesc: 'Deployment starts automatically after approval; the result is reported separately.',
  viewRequest: 'View request',
  backToWorkbench: 'Back to workbench',

  requestsTitle: 'My requests',
  requestsDesc: 'Only requests submitted by the current user are shown.',
  colReqName: 'Name',
  colReqTime: 'Submitted',
  colReqApproval: 'Approval',
  colReqDeploy: 'Deployment',
  colReqAction: 'Actions',
  actionView: 'View',
  reqStatePending: 'Pending',
  reqStateApproved: 'Approved',
  reqStateRejected: 'Rejected',
  reqStateDeployed: 'Created',
  reqStateUnknown: 'Unknown state',
  deployNotStarted: 'Not started',
  deployRejected: 'Not deployed',
  deployGone: 'Deployment record is gone',
  deployUnknown: 'Unknown',
  filterAll: 'All',
  requestsEmpty: 'No requests yet.',
  requestsFailed: 'Failed to load the request list.',
  detailFailed: 'Failed to load the request.',
  detailNotFound: 'This request does not exist or is not yours.',
  detailTitle: 'Request detail',
  detailApplicant: 'Requester',
  detailTeam: 'Owning team',
  detailPurpose: 'Purpose',
  detailNote: 'Notes',
  detailModel: 'Model',
  detailApproval: 'Approval result',
  detailDeploy: 'Deployment result',
  detailRejectedReason: 'Rejection reason',
  timelineDecidedBy: 'Approver',
  backToRequests: 'Back to requests',
  notProvided: '—',
};

export const workbenchCopy: Record<AdminLanguage, Record<keyof typeof zh, string>> = { zh, en };

export type WorkbenchCopyKey = keyof typeof zh;

export function workbenchT(key: WorkbenchCopyKey, language: AdminLanguage = 'zh'): string {
  return workbenchCopy[language][key];
}
